const fs = require("fs");
const path = require("path");
const { URL } = require("url");

const DEFAULT_COOKIES_PATH = path.resolve(process.cwd(), "cookies.json");
const PARAVERSE_HOST = "paraverse.feutech.edu.ph";

function readCookieFile(cookiesPath) {
  const filePath = cookiesPath || DEFAULT_COOKIES_PATH;
  if (!fs.existsSync(filePath)) {
    const err = new Error(
      `Cookie jar not found at ${filePath}. ` +
      `Run \`npm run cookies:snippet\` for instructions on how to populate it.`
    );
    err.code = "COOKIES_MISSING";
    throw err;
  }

  const raw = fs.readFileSync(filePath, "utf8").trim();
  if (!raw) {
    const err = new Error(`Cookie jar at ${filePath} is empty.`);
    err.code = "COOKIES_EMPTY";
    throw err;
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (parseErr) {
    const err = new Error(`Cookie jar at ${filePath} is not valid JSON: ${parseErr.message}`);
    err.code = "COOKIES_INVALID";
    throw err;
  }

  if (!Array.isArray(parsed)) {
    const err = new Error(`Cookie jar at ${filePath} must be a JSON array of cookie objects.`);
    err.code = "COOKIES_INVALID";
    throw err;
  }

  return parsed;
}

function normalizeCookie(cookie) {
  if (!cookie || typeof cookie !== "object") {
    return null;
  }
  const name = String(cookie.name || "").trim();
  if (!name) {
    return null;
  }
  return {
    name,
    value: String(cookie.value == null ? "" : cookie.value),
    domain: String(cookie.domain || PARAVERSE_HOST).trim(),
    path: String(cookie.path || "/").trim() || "/",
    expires: typeof cookie.expires === "number" ? cookie.expires : -1,
    httpOnly: Boolean(cookie.httpOnly),
    secure: Boolean(cookie.secure),
    sameSite: cookie.sameSite || "Lax"
  };
}

function loadCookies(cookiesPath) {
  return readCookieFile(cookiesPath)
    .map(normalizeCookie)
    .filter(Boolean);
}

function domainMatches(cookieDomain, hostname) {
  const cd = cookieDomain.toLowerCase().replace(/^\./, "");
  const host = hostname.toLowerCase();
  return host === cd || host.endsWith(`.${cd}`);
}

function pathMatches(cookiePath, requestPath) {
  if (!cookiePath || cookiePath === "/") {
    return true;
  }
  if (requestPath === cookiePath) {
    return true;
  }
  if (requestPath.startsWith(cookiePath)) {
    const next = requestPath.charAt(cookiePath.length);
    return cookiePath.endsWith("/") || next === "/" || next === "";
  }
  return false;
}

function toCookieHeader(cookies, url) {
  const parsed = new URL(url);
  const nowSec = Math.floor(Date.now() / 1000);
  const matching = cookies.filter((c) => {
    if (c.expires > 0 && c.expires < nowSec) {
      return false;
    }
    if (!domainMatches(c.domain, parsed.hostname)) {
      return false;
    }
    if (!pathMatches(c.path, parsed.pathname || "/")) {
      return false;
    }
    if (c.secure && parsed.protocol !== "https:") {
      return false;
    }
    return true;
  });

  return matching.map((c) => `${c.name}=${c.value}`).join("; ");
}

function toNetscapeFormat(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by paraverse-module-translator — do not commit",
    ""
  ];
  for (const c of cookies) {
    const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
    const includeSubdomains = "TRUE";
    const cookiePath = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expires = c.expires > 0 ? Math.floor(c.expires) : 0;
    lines.push([domain, includeSubdomains, cookiePath, secure, expires, c.name, c.value].join("\t"));
  }
  return `${lines.join("\n")}\n`;
}

function writeNetscapeFile(cookies, outputPath) {
  fs.writeFileSync(outputPath, toNetscapeFormat(cookies), "utf8");
  return outputPath;
}

function hasParaverseSession(cookies) {
  const nowSec = Math.floor(Date.now() / 1000);
  return cookies.some((c) => {
    if (!domainMatches(c.domain, PARAVERSE_HOST)) {
      return false;
    }
    if (c.expires > 0 && c.expires < nowSec) {
      return false;
    }
    return /sess|laravel|csrf|xsrf|token/i.test(c.name);
  });
}

function isExpired(cookies) {
  if (!cookies.length) {
    return true;
  }
  return !hasParaverseSession(cookies);
}

module.exports = {
  DEFAULT_COOKIES_PATH,
  PARAVERSE_HOST,
  loadCookies,
  toCookieHeader,
  toNetscapeFormat,
  writeNetscapeFile,
  isExpired,
  hasParaverseSession
};
